name: 'Update Package Version from Release Branch'
description:
  'Automatically update the package version based on the branch name when there
  is a push to a release branch.'
author: 'David Velásquez'

runs:
  using: node20
  main: dist/index.js

branding:
  icon: arrow-up-circle
  color: green
